export const CONTACT_PRESSED = 'CONTACT_PRESSED';
export const WATCH_PRESSED = 'WATCH_PRESSED';
export const LISTEN_PRESSED = 'LISTEN_PRESSED';
export const GIGS_PRESSED = 'GIGS_PRESSED';
export const VIDEO_FETCH_SUCCESS = 'VIDEO_FETCH_SUCCESS';
